version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  build:
    working_directory: ~/bugzilla
    docker:
      - image: circleci/ruby:2.6.3
        environment:
          BUGZILA_TEST_DB_USER: bugzilla
          BUGZILA_TEST_DB_PASSWORD: password
          RAILS_ENV: test
      - image: postgres:9.5
        environment:
          POSTGRES_USER: bugzilla
          POSTGRES_DB: bugzilla_test
          POSTGRES_PASSWORD: password
    steps:
      - checkout

      # Bundle install dependencies
      - run: bundle install --path vendor/bundle

      # Wait for DB
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run: cp .sample.env .env

      # Setup the database
      - run: bundle exec rake db:setup

      # Run the tests
      - run: bundle exec rspec
