development:
  adapter: postgresql
  encoding: unicode
  database: bugzilla_development
  pool: 5
  timeout: 5000
  host: localhost
  username: <%= ENV['BUGZILA_DEV_DB_USER'] %>
  password: <%= ENV['BUGZILA_DEV_DB_PASSWORD'] %>

test:
  adapter: postgresql
  encoding: unicode
  database: bugzilla_test
  pool: 5
  timeout: 5000
  host: localhost
  username: <%= ENV['BUGZILA_TEST_DB_USER'] %>
  password: <%= ENV['BUGZILA_TEST_DB_PASSWORD'] %>

production:
  url:  <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV["DB_POOL"] || ENV['MAX_THREADS'] || 1 %>
  prepared_statements: false
